### ISSUE TITLE
Error when installing due to missing LICENSE file

### ISSUE THREAD

**Issue by michaelgmiller** [dizballanze/django-compressor-autoprefixer#1]
Hi there,

When I run `pip install django-compressor-autoprefixer`, I get an error `error: can't copy 'LICENSE': doesn't exist or not a regular file`. It looks like the `LICENSE` file is not included in the package published to `PyPI`. Can you re-publish the package with the `LICENSE` file?

Thanks!
Mike

**Comment by dizballanze** [comment]
Hi, thank you for the notice.
I had fixed it and uploaded new version to PyPI.
